///|
fn typed_encode_template_70(template : Grib2DataTemplate70) -> Bytes {
  template.data_values_raw
}

///|
fn typed_encode_template_71(template : Grib2DataTemplate71) -> Bytes {
  template.data_values_raw
}

///|
fn typed_encode_template_72(template : Grib2DataTemplate72) -> Bytes {
  template.data_values_raw
}

///|
fn typed_encode_template_73(template : Grib2DataTemplate73) -> Bytes {
  template.data_values_raw
}

///|
fn typed_encode_template_74(template : Grib2DataTemplate74) -> Bytes {
  template.data_values_raw
}

///|
fn typed_encode_template_740(template : Grib2DataTemplate740) -> Bytes {
  template.data_values_raw
}

///|
fn typed_encode_template_741(template : Grib2DataTemplate741) -> Bytes {
  template.data_values_raw
}

///|
fn typed_encode_template_742(template : Grib2DataTemplate742) -> Bytes {
  template.data_values_raw
}

///|
fn typed_encode_template_750(template : Grib2DataTemplate750) -> Bytes {
  template.data_values_raw
}

///|
fn typed_encode_template_751(template : Grib2DataTemplate751) -> Bytes {
  template.data_values_raw
}

///|
fn typed_encode_template_753(template : Grib2DataTemplate753) -> Bytes {
  template.data_values_raw
}
