///|
fn typed_decode_template_70(
  payload : Bytes,
) -> Result[Grib2DataTemplate70, Grib2SectionCodecError] {
  Ok({ data_values_raw: payload })
}

///|
fn typed_decode_template_71(
  payload : Bytes,
) -> Result[Grib2DataTemplate71, Grib2SectionCodecError] {
  Ok({ data_values_raw: payload })
}

///|
fn typed_decode_template_72(
  payload : Bytes,
) -> Result[Grib2DataTemplate72, Grib2SectionCodecError] {
  Ok({ data_values_raw: payload })
}

///|
fn typed_decode_template_73(
  payload : Bytes,
) -> Result[Grib2DataTemplate73, Grib2SectionCodecError] {
  Ok({ data_values_raw: payload })
}

///|
fn typed_decode_template_74(
  payload : Bytes,
) -> Result[Grib2DataTemplate74, Grib2SectionCodecError] {
  Ok({ data_values_raw: payload })
}

///|
fn typed_decode_template_740(
  payload : Bytes,
) -> Result[Grib2DataTemplate740, Grib2SectionCodecError] {
  Ok({ data_values_raw: payload })
}

///|
fn typed_decode_template_741(
  payload : Bytes,
) -> Result[Grib2DataTemplate741, Grib2SectionCodecError] {
  Ok({ data_values_raw: payload })
}

///|
fn typed_decode_template_742(
  payload : Bytes,
) -> Result[Grib2DataTemplate742, Grib2SectionCodecError] {
  Ok({ data_values_raw: payload })
}

///|
fn typed_decode_template_750(
  payload : Bytes,
) -> Result[Grib2DataTemplate750, Grib2SectionCodecError] {
  Ok({ data_values_raw: payload })
}

///|
fn typed_decode_template_751(
  payload : Bytes,
) -> Result[Grib2DataTemplate751, Grib2SectionCodecError] {
  Ok({ data_values_raw: payload })
}

///|
fn typed_decode_template_753(
  payload : Bytes,
) -> Result[Grib2DataTemplate753, Grib2SectionCodecError] {
  Ok({ data_values_raw: payload })
}
