/**
 * GRIB2 WASM Module Type Definitions
 */

// =============================================================================
// Section Data Types (Low-Level API)
// =============================================================================

/**
 * Section 1: Identification Section data
 */
export interface Section1Data {
  center: number;
  subcenter: number;
  masterTableVersion: number;
  localTableVersion: number;
  significanceOfRefTime: number;
  year: number;
  month: number;
  day: number;
  hour: number;
  minute: number;
  second: number;
  productionStatus: number;
  typeOfData: number;
}

/**
 * Section 3: Grid Definition Section data
 */
export interface Section3Data {
  template: number;
  gridDefinitionSource: number;
  numberOfPoints: number;
  ni?: number;
  nj?: number;
  lat1Microdeg?: number;
  lon1Microdeg?: number;
  lat2Microdeg?: number;
  lon2Microdeg?: number;
  diMicrodeg?: number;
  djMicrodeg?: number;
  scanMode?: number;
  resolutionFlags?: number;
}

/**
 * Section 4: Product Definition Section data
 */
export interface Section4Data {
  template: number;
  parameterCategory?: number;
  parameterNumber?: number;
  typeOfGeneratingProcess?: number;
  indicatorOfUnitOfTimeRange?: number;
  forecastTime?: number;
  typeOfFirstFixedSurface?: number;
  scaleFactorOfFirstFixedSurface?: number;
  scaledValueOfFirstFixedSurface?: number;
  typeOfSecondFixedSurface?: number | null;
  scaleFactorOfSecondFixedSurface?: number | null;
  scaledValueOfSecondFixedSurface?: number | null;
  // Template-specific optional fields
  ensembleType?: number;
  perturbationNumber?: number;
  numberOfEnsembleMembers?: number;
  probabilityType?: number;
}

/**
 * Section 5: Data Representation Section data
 */
export interface Section5Data {
  template: number;
  numberOfPoints: number;
  referenceValue?: number;
  binaryScaleFactor?: number;
  decimalScaleFactor?: number;
  bitsPerValue?: number;
}

/**
 * Section 6: Bit-Map Section data
 */
export interface Section6Data {
  bitmapIndicator: number;
}

// AUTO-GENERATED:WASM-FUNCTIONS START
// This block is generated by scripts/generate-wasm-dts.mjs.
// Do not edit manually.
export function init(): Promise<void>;
export function initBrowser(wasmUrl: string | URL): Promise<void>;
export function parseGrib2(data: Uint8Array): number;
export function getMessageCount(handle: number): number;
export function getRecordCount(handle: number): number;
export function getSection1(handle: number, messageIndex: number): Section1Data;
export function getSection3(handle: number, recordIndex: number): Section3Data;
export function getSection4(handle: number, recordIndex: number): Section4Data;
export function getSection5(handle: number, recordIndex: number): Section5Data;
export function getSection6(handle: number, recordIndex: number): Section6Data;
export function getLatitudes(handle: number, recordIndex: number): Float32Array;
export function getLongitudes(handle: number, recordIndex: number): Float32Array;
export function getGridData(handle: number, recordIndex: number): Float32Array;
// AUTO-GENERATED:WASM-FUNCTIONS END
